name: musix_admin
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  logging: ^1.2.0
  get_it: ^7.6.0
  intl: ^0.18.1
  dio: ^5.2.1+1
  data_table_2: ^2.4.2
  chewie: ^1.7.0
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/
